# Generated by Django 4.2.13 on 2024-05-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appallsaint', '0002_categoryitem_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='categories',
        ),
    ]
